apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: simple-nodejs-app-kjfy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-korc-tenant/nodejs-users/simple-nodejs-app-kjfy@sha256:ece92d23036a1f88d31fe8ed854d3005a4679a0cb20f32b0aa146ad9a2e51210
        name: my-nodejs
        resources: {}
status: {}
